
import { Question } from './types';

export const QUESTIONS: Question[] = [
  // ===== NUMBER SERIES / PATTERN RECOGNITION (q1–q25) =====
  { id: "q1", text: "What comes next in the series: 2, 6, 18, 54, ...?", options: ["108", "162", "72", "96"] },
  { id: "q2", text: "What comes next: 3, 5, 9, 17, 33, ...?", options: ["49", "57", "65", "61"] },
  { id: "q3", text: "Complete the series: 1, 4, 9, 16, 25, ...?", options: ["30", "36", "49", "32"] },
  { id: "q4", text: "What comes next: 2, 3, 5, 7, 11, 13, ...?", options: ["15", "17", "19", "14"] },
  { id: "q5", text: "Complete the series: 1, 1, 2, 3, 5, 8, 13, ...?", options: ["18", "20", "21", "26"] },
  { id: "q6", text: "What number replaces the '?': 4, 9, 25, 49, 121, ?", options: ["144", "169", "196", "225"] },
  { id: "q7", text: "Complete the pattern: 100, 98, 94, 86, 70, ...?", options: ["38", "46", "54", "30"] },
  { id: "q8", text: "What comes next: 1, 8, 27, 64, 125, ...?", options: ["196", "216", "250", "343"] },
  { id: "q9", text: "Find the next number: 5, 11, 23, 47, 95, ...?", options: ["190", "191", "185", "197"] },
  { id: "q10", text: "What comes next: 2, 5, 10, 17, 26, ...?", options: ["35", "37", "39", "41"] },
  { id: "q11", text: "Complete: 720, 120, 24, 6, 2, ...?", options: ["1", "0", "0.5", "3"] },
  { id: "q12", text: "What comes next: 3, 6, 11, 18, 27, ...?", options: ["36", "38", "39", "42"] },
  { id: "q13", text: "Find the missing number: 2, 6, 12, 20, 30, ?", options: ["42", "40", "44", "36"] },
  { id: "q14", text: "What comes next: 1, 3, 7, 15, 31, ...?", options: ["47", "55", "63", "59"] },
  { id: "q15", text: "Complete: 256, 64, 16, 4, ...?", options: ["1", "2", "0", "0.5"] },
  { id: "q16", text: "What is the next number: 0, 1, 1, 2, 4, 7, 13, ...?", options: ["20", "24", "21", "26"] },
  { id: "q17", text: "Complete: 1, 2, 6, 24, 120, ...?", options: ["480", "600", "720", "840"] },
  { id: "q18", text: "Find the next term: 11, 13, 17, 19, 23, 29, ...?", options: ["31", "33", "35", "37"] },
  { id: "q19", text: "What replaces '?': 2, 3, 5, 9, 17, ?", options: ["33", "27", "25", "31"] },
  { id: "q20", text: "Complete the series: 1, 4, 13, 40, 121, ...?", options: ["364", "242", "363", "484"] },
  { id: "q21", text: "What comes next: 8, 6, 7, 5, 6, 4, ...?", options: ["5", "3", "2", "7"] },
  { id: "q22", text: "Find the next number: 3, 4, 7, 11, 18, 29, ...?", options: ["47", "40", "45", "52"] },
  { id: "q23", text: "Complete: 1, 3, 6, 10, 15, 21, ...?", options: ["25", "27", "28", "30"] },
  { id: "q24", text: "What comes next: 2, 8, 18, 32, 50, ...?", options: ["72", "68", "74", "80"] },
  { id: "q25", text: "Find the pattern: 99, 92, 86, 81, 77, ...?", options: ["74", "72", "70", "73"] },

  // ===== LOGICAL REASONING (q26–q45) =====
  { id: "q26", text: "All roses are flowers. Some flowers fade quickly. Which statement must be true?", options: ["All roses fade quickly", "Some roses may fade quickly", "No roses fade quickly", "All flowers are roses"] },
  { id: "q27", text: "If all Zips are Zaps, and all Zaps are Zops, which must be true?", options: ["All Zops are Zips", "All Zips are Zops", "Some Zops are not Zaps", "No Zips are Zops"] },
  { id: "q28", text: "Statement: No fish can fly. All sparrows can fly. Conclusion: No sparrow is a fish.", options: ["True", "False", "Cannot be determined", "Partly true"] },
  { id: "q29", text: "If it rains, the ground gets wet. The ground is not wet. What can you conclude?", options: ["It rained", "It did not rain", "It might have rained", "The ground is dry sometimes"] },
  { id: "q30", text: "A is taller than B. C is shorter than B. D is taller than A. Who is the shortest?", options: ["A", "B", "C", "D"] },
  { id: "q31", text: "If all dogs have tails and Rex has a tail, what can we conclude?", options: ["Rex is a dog", "Rex might be a dog", "Rex is definitely not a dog", "All tailed animals are dogs"] },
  { id: "q32", text: "P is east of Q. R is north of P. S is west of R. S is in which direction relative to Q?", options: ["North", "North-East", "North-West", "East"] },
  { id: "q33", text: "In a row of students, Amit is 7th from the left and 15th from the right. How many students are in the row?", options: ["20", "21", "22", "23"] },
  { id: "q34", text: "If CLOUD is coded as DMPVE, what is RAIN coded as?", options: ["SBJO", "SZHO", "SBJM", "RAJO"] },
  { id: "q35", text: "If Monday falls on the 1st of a month, what day will the 23rd be?", options: ["Monday", "Tuesday", "Wednesday", "Thursday"] },
  { id: "q36", text: "Statement: Some teachers are doctors. All doctors are engineers. Conclusion: Some teachers are engineers.", options: ["True", "False", "Cannot be determined", "Only sometimes"] },
  { id: "q37", text: "If A + B means A is the father of B, and A - B means A is the sister of B, what does P + Q - R mean?", options: ["R is the niece/nephew of P", "P is the father of Q who is the sister of R", "R is the father of Q", "P is the sister of R"] },
  { id: "q38", text: "A is B's brother. C is B's mother. D is C's father. E is D's mother. How is A related to D?", options: ["Grandson", "Son", "Grandfather", "Nephew"] },
  { id: "q39", text: "If you rearrange the letters 'CIFAIPC', you get the name of a(n):", options: ["Country", "City", "Ocean", "Animal"] },
  { id: "q40", text: "Pointing at a man, Sara said 'His mother is the only daughter of my mother.' How is Sara related to the man?", options: ["Mother", "Sister", "Aunt", "Grandmother"] },
  { id: "q41", text: "Which conclusion follows: All pens are roads. All roads are houses.", options: ["All pens are houses", "All houses are pens", "Some roads are pens", "No pen is a house"] },
  { id: "q42", text: "If 'SEND' is written as '5149' and 'MORE' is written as '6380', what is 'DONE'?", options: ["9314", "9014", "4190", "4391"] },
  { id: "q43", text: "In a certain code, 'MOUSE' is written as 'PRXVH'. How is 'CHAIR' written?", options: ["FKDLU", "FKDLR", "EKDLU", "FLDKU"] },
  { id: "q44", text: "If South-East becomes North, what does North-East become?", options: ["South", "West", "North-West", "South-West"] },
  { id: "q45", text: "Five friends are sitting in a row. A is to the left of B and to the right of C. D is to the right of B. E is at the left end. Who is in the middle?", options: ["A", "B", "C", "D"] },

  // ===== VERBAL ANALOGIES (q46–q65) =====
  { id: "q46", text: "Architect is to Blueprint as Composer is to:", options: ["Music", "Score", "Song", "Orchestra"] },
  { id: "q47", text: "Marathon is to Race as Hibernation is to:", options: ["Sleep", "Winter", "Bear", "Dream"] },
  { id: "q48", text: "Telescope is to Stars as Microscope is to:", options: ["Bacteria", "Lens", "Laboratory", "Slide"] },
  { id: "q49", text: "Famished is to Hungry as Exhausted is to:", options: ["Tired", "Active", "Sleepy", "Lazy"] },
  { id: "q50", text: "Enigma is to Puzzle as Labyrinth is to:", options: ["Maze", "Garden", "Path", "Tower"] },
  { id: "q51", text: "Seed is to Tree as Egg is to:", options: ["Chicken", "Bird", "Nest", "Shell"] },
  { id: "q52", text: "Scalpel is to Surgeon as Chisel is to:", options: ["Carpenter", "Sculptor", "Painter", "Blacksmith"] },
  { id: "q53", text: "Pedal is to Bicycle as Oar is to:", options: ["Boat", "Water", "Paddle", "River"] },
  { id: "q54", text: "Thermometer is to Temperature as Barometer is to:", options: ["Pressure", "Humidity", "Wind", "Altitude"] },
  { id: "q55", text: "Prologue is to Beginning as Epilogue is to:", options: ["End", "Middle", "Sequel", "Summary"] },
  { id: "q56", text: "Cacophony is to Sound as Chaos is to:", options: ["Order", "Disorder", "Noise", "Confusion"] },
  { id: "q57", text: "Optimist is to Hopeful as Pessimist is to:", options: ["Cynical", "Cheerful", "Realistic", "Neutral"] },
  { id: "q58", text: "Chapter is to Book as Scene is to:", options: ["Play", "Movie", "Act", "Stage"] },
  { id: "q59", text: "Evaporation is to Liquid as Sublimation is to:", options: ["Solid", "Gas", "Plasma", "Vapour"] },
  { id: "q60", text: "Constellation is to Stars as Archipelago is to:", options: ["Islands", "Mountains", "Oceans", "Rivers"] },
  { id: "q61", text: "Apex is to Peak as Nadir is to:", options: ["Bottom", "Middle", "Side", "Top"] },
  { id: "q62", text: "Chronology is to Time as Cartography is to:", options: ["Maps", "Stars", "Books", "Numbers"] },
  { id: "q63", text: "Caterpillar is to Butterfly as Tadpole is to:", options: ["Frog", "Fish", "Salamander", "Toad"] },
  { id: "q64", text: "Drought is to Rain as Famine is to:", options: ["Food", "Water", "Hunger", "Poverty"] },
  { id: "q65", text: "Fossil is to Prehistoric as Artifact is to:", options: ["Historical", "Modern", "Ancient", "Futuristic"] },

  // ===== SPATIAL / VISUAL REASONING (q66–q80) =====
  { id: "q66", text: "If you fold a square piece of paper in half diagonally, what shape do you get?", options: ["Triangle", "Rectangle", "Pentagon", "Trapezoid"] },
  { id: "q67", text: "How many faces does a cube have?", options: ["4", "6", "8", "12"] },
  { id: "q68", text: "A cube is painted red on all faces then cut into 27 equal smaller cubes. How many small cubes have exactly 2 red faces?", options: ["8", "12", "6", "1"] },
  { id: "q69", text: "Which shape is the odd one out: Circle, Oval, Triangle, Ellipse?", options: ["Circle", "Oval", "Triangle", "Ellipse"] },
  { id: "q70", text: "A cube is painted blue on all sides and cut into 64 equal cubes. How many cubes have no painted face?", options: ["8", "16", "24", "0"] },
  { id: "q71", text: "If you look at a clock in a mirror showing 3:15, what time does the mirror image show?", options: ["8:45", "9:45", "6:45", "9:15"] },
  { id: "q72", text: "How many triangles are in a figure made of a triangle divided into 4 smaller triangles by connecting midpoints?", options: ["5", "8", "6", "4"] },
  { id: "q73", text: "A piece of paper is folded once and a hole is punched. When unfolded, how many holes appear?", options: ["1", "2", "3", "4"] },
  { id: "q74", text: "Which 3D shape has 5 faces, 8 edges, and 5 vertices?", options: ["Square pyramid", "Triangular prism", "Cube", "Tetrahedron"] },
  { id: "q75", text: "If you rotate the letter 'N' by 90° clockwise, which letter does it most resemble?", options: ["Z", "M", "W", "S"] },
  { id: "q76", text: "A cube has each face a different color. If you can see 3 faces at once, how many colors are hidden?", options: ["2", "3", "4", "1"] },
  { id: "q77", text: "How many edges does a triangular prism have?", options: ["6", "8", "9", "12"] },
  { id: "q78", text: "If the hour hand of a clock moves 30° in one hour, how many degrees does it move in 20 minutes?", options: ["10°", "15°", "20°", "5°"] },
  { id: "q79", text: "Which shape has the most lines of symmetry?", options: ["Equilateral triangle", "Square", "Regular hexagon", "Circle"] },
  { id: "q80", text: "If you cut a cone parallel to its base, what shape is the cross-section?", options: ["Circle", "Ellipse", "Triangle", "Parabola"] },

  // ===== MATHEMATICAL REASONING (q81–q90) =====
  { id: "q81", text: "If 3 workers can build 3 walls in 3 days, how many days do 9 workers need to build 9 walls?", options: ["1", "3", "9", "27"] },
  { id: "q82", text: "A bat and a ball cost $1.10 total. The bat costs $1.00 more than the ball. How much is the ball?", options: ["$0.10", "$0.05", "$0.15", "$0.01"] },
  { id: "q83", text: "In a lake, there is a patch of lily pads. Every day, the patch doubles in size. It takes 48 days to cover the entire lake. On what day was the lake half covered?", options: ["24", "36", "47", "40"] },
  { id: "q84", text: "If 5 cats catch 5 mice in 5 minutes, how many cats are needed to catch 100 mice in 100 minutes?", options: ["5", "10", "20", "100"] },
  { id: "q85", text: "A snail climbs 3 meters during the day and slides back 2 meters at night. How many days to climb a 10-meter wall?", options: ["8", "10", "7", "9"] },
  { id: "q86", text: "What is the minimum number of socks you must pull from a drawer containing 10 black and 10 white socks to guarantee a matching pair?", options: ["2", "3", "11", "12"] },
  { id: "q87", text: "Two trains are 200 km apart heading toward each other at 50 km/h each. A fly starts at one train and flies at 75 km/h back and forth. How far does the fly travel before the trains meet?", options: ["100 km", "150 km", "200 km", "75 km"] },
  { id: "q88", text: "If you have 12 coins and one is counterfeit (lighter). Using a balance scale, what is the minimum number of weighings to find it?", options: ["2", "3", "4", "6"] },
  { id: "q89", text: "A clock chimes 6 times in 5 seconds. How many seconds does it take to chime 12 times?", options: ["10", "11", "12", "10.5"] },
  { id: "q90", text: "What fraction of a day is 6 hours?", options: ["1/6", "1/4", "1/3", "1/8"] },

  // ===== MATRIX / PATTERN COMPLETION (q91–q100) =====
  { id: "q91", text: "In a 3×3 grid, each row has Circle, Square, Triangle. Each column has Red, Blue, Green. What shape and color is in the missing cell (row 3, col 3)?", options: ["Red Circle", "Blue Triangle", "Green Square", "Red Square"] },
  { id: "q92", text: "Each row increases by +1, +2, +3. Row 1: 1, 2, 4, 7. Row 2: 2, 3, 5, 8. What is the first number in Row 3?", options: ["3", "4", "5", "6"] },
  { id: "q93", text: "In each row the numbers are: 2, 4, 8 | 3, 9, 27 | 4, 16, ? — What is '?'?", options: ["32", "48", "64", "128"] },
  { id: "q94", text: "Pattern: Row 1 has 1 dot. Row 2 has 3 dots. Row 3 has 6 dots. How many dots in Row 5?", options: ["10", "12", "15", "21"] },
  { id: "q95", text: "Each cell in a row follows: multiply by 2, then subtract 1. Starting with 3: 3, 5, 9, 17. Starting with 4: 4, 7, 13, ?", options: ["25", "23", "27", "21"] },
  { id: "q96", text: "In each row the pattern is ×2, ×3: Row 1: 1, 2, 6. Row 2: 2, 4, 12. Row 3: 3, ?, 18. What is '?'?", options: ["6", "9", "12", "5"] },
  { id: "q97", text: "A 2×2 grid: top-left is 2, top-right is 3, bottom-left is 4, bottom-right is X. If each row's product equals the next row's sum multiplied by 2, what is X?", options: ["6", "3", "5", "8"] },
  { id: "q98", text: "Pattern: A, 1, B, 4, C, 9, D, 16, E, ? — What is '?'?", options: ["20", "25", "36", "22"] },
  { id: "q99", text: "In a sequence of shapes: ○ □ △ ○ □ △ ○ □ ? — What comes next?", options: ["○", "□", "△", "◇"] },
  { id: "q100", text: "Each row sums to the same total. Row 1: 8, 1, 6. Row 2: 3, 5, 7. Row 3: 4, 9, ?", options: ["2", "3", "5", "6"] },
];

export const APP_THEME = {
  background: "#0f0f0f",
  primary: "#3b82f6", // Blue
  secondary: "#8b5cf6", // Purple
  accent: "#06b6d4" // Cyan
};
