
import { Question } from './types';

export const QUESTIONS: Question[] = [
  // 1-10
  { id: "q1", text: "Which number follows the series: 2, 4, 8, 16, ...?", options: ["24", "30", "32", "64"] },
  { id: "q2", text: "If all Bloops are Razzies and all Razzies are Lazzies, then all Bloops are definitely Lazzies.", options: ["True", "False", "Cannot tell"] },
  { id: "q3", text: "Rearrange 'OCEAN' to name a country. (Choose the correct starting letter)", options: ["F", "I", "N", "None of these"] },
  { id: "q4", text: "What is 15% of 2000?", options: ["250", "300", "350", "400"] },
  { id: "q5", text: "Book is to Reading as Fork is to...", options: ["Drawing", "Eating", "Writing", "Stirring"] },
  { id: "q6", text: "Which word does not belong with the others?", options: ["Parsley", "Basil", "Dill", "Apple"] },
  { id: "q7", text: "If you rotate a square 45 degrees, how many corners does it have?", options: ["4", "8", "0", "Infinite"] },
  { id: "q8", text: "One-fourth of one-half of one-fifth of 200 is:", options: ["2", "5", "10", "20"] },
  { id: "q9", text: "A man is 24 years older than his son. In 2 years, he will be twice his son's age. Son's current age:", options: ["20", "22", "24", "18"] },
  { id: "q10", text: "Find the odd one out: Circle, Sphere, Cube, Pyramid.", options: ["Circle", "Sphere", "Cube", "Pyramid"] },
  // 11-20
  { id: "q11", text: "Which number is next? 1, 1, 2, 3, 5, 8, ...", options: ["10", "11", "12", "13"] },
  { id: "q12", text: "If 5 machines take 5 minutes to make 5 widgets, how long does it take 100 machines to make 100 widgets?", options: ["100 min", "50 min", "5 min", "1 min"] },
  { id: "q13", text: "Which word is the opposite of 'Stagnant'?", options: ["Still", "Flowing", "Dirty", "Old"] },
  { id: "q14", text: "A bat and a ball cost $1.10. The bat costs $1.00 more than the ball. How much is the ball?", options: ["$0.10", "$0.05", "$0.15", "$0.01"] },
  { id: "q15", text: "Finger is to Hand as Leaf is to...", options: ["Tree", "Branch", "Twig", "Forest"] },
  { id: "q16", text: "If you scramble the letters 'NEWYORK', you get a:", options: ["Fruit", "City", "Animal", "Country"] },
  { id: "q17", text: "Which number is the smallest?", options: ["0.5", "1/4", "0.33", "2/5"] },
  { id: "q18", text: "Mary is 16. She is 4 times as old as her brother. How old will she be when she is twice as old?", options: ["20", "24", "28", "32"] },
  { id: "q19", text: "Which shape is 3D?", options: ["Triangle", "Square", "Cylinder", "Circle"] },
  { id: "q20", text: "Ocean is to Water as Glacier is to...", options: ["Cold", "Mountain", "Ice", "Winter"] },
  // 21-30
  { id: "q21", text: "Which number follows: 100, 95, 85, 70, ...?", options: ["50", "60", "55", "45"] },
  { id: "q22", text: "Choose the word most similar to 'Profound':", options: ["Deep", "Surface", "Quick", "Light"] },
  { id: "q23", text: "How many months have 28 days?", options: ["1", "6", "12", "Depends on the year"] },
  { id: "q24", text: "Which letter comes next? A, C, E, G, ...", options: ["H", "I", "J", "K"] },
  { id: "q25", text: "7 + 7 / 7 + 7 * 7 - 7 = ?", options: ["0", "50", "49", "56"] },
  { id: "q26", text: "If 1=5, 2=25, 3=125, 4=625, then 5=?", options: ["3125", "1", "5", "1000"] },
  { id: "q27", text: "Which is the odd one out?", options: ["North", "West", "South", "Up"] },
  { id: "q28", text: "A snail is in a 30ft well. It climbs 3ft/day but slips 2ft/night. How many days to reach the top?", options: ["30", "29", "28", "27"] },
  { id: "q29", text: "What is the square root of 144?", options: ["10", "11", "12", "14"] },
  { id: "q30", text: "A father has 4 daughters. Each daughter has a brother. How many children in total?", options: ["8", "5", "4", "9"] },
  // 31-40
  { id: "q31", text: "Next in series: 3, 6, 11, 18, ...?", options: ["25", "27", "29", "31"] },
  { id: "q32", text: "Light is to Dark as Knowledge is to...", options: ["Power", "Wisdom", "Ignorance", "Books"] },
  { id: "q33", text: "Rearrange 'RAPE' to name a fruit:", options: ["Apple", "Pear", "Grape", "Peach"] },
  { id: "q34", text: "If you have 3 apples and you take away 2, how many do you have?", options: ["1", "2", "3", "0"] },
  { id: "q35", text: "Which is heavier: a pound of gold or a pound of feathers?", options: ["Gold", "Feathers", "Both equal", "Depends on volume"] },
  { id: "q36", text: "Which word doesn't fit?", options: ["Oboe", "Flute", "Violin", "Clarinet"] },
  { id: "q37", text: "A doctor gives you 3 pills and tells you to take one every half hour. How long do they last?", options: ["1.5 hrs", "1 hr", "2 hrs", "30 mins"] },
  { id: "q38", text: "Which number is one-tenth of one-fifth of 100?", options: ["2", "10", "5", "20"] },
  { id: "q39", text: "Mountain is to High as Valley is to...", options: ["Low", "Green", "Flat", "River"] },
  { id: "q40", text: "Some months have 31 days, some have 30. How many have 28?", options: ["1", "4", "12", "0"] },
  // 41-50
  { id: "q41", text: "Next in series: 1, 4, 9, 16, 25, ...?", options: ["30", "34", "36", "40"] },
  { id: "q42", text: "If 'CAT' is '3120', what is 'DOG'?", options: ["4157", "41520", "4150", "4015"] },
  { id: "q43", text: "Which is the odd one out?", options: ["Mars", "Venus", "Moon", "Saturn"] },
  { id: "q44", text: "If you flip a coin 3 times, what is the probability of 3 heads?", options: ["1/2", "1/4", "1/8", "1/6"] },
  { id: "q45", text: "A farmer has 17 sheep. All but 9 die. How many are left?", options: ["8", "9", "0", "17"] },
  { id: "q46", text: "Which word means the same as 'Candid'?", options: ["Honest", "Sweet", "Hidden", "Smart"] },
  { id: "q47", text: "Which number is prime?", options: ["9", "15", "21", "23"] },
  { id: "q48", text: "If today is Monday, what day is 62 days from now?", options: ["Monday", "Tuesday", "Saturday", "Sunday"] },
  { id: "q49", text: "Camera is to Photographer as Brush is to...", options: ["Canvas", "Paint", "Artist", "Wall"] },
  { id: "q50", text: "What comes next: O, T, T, F, F, S, S, ...?", options: ["S", "E", "N", "T"] },
  // 51-60
  { id: "q51", text: "Next in series: 2, 3, 5, 7, 11, ...?", options: ["12", "13", "15", "17"] },
  { id: "q52", text: "If 12 + 12 = 9, 23 + 23 = 16, then 34 + 34 = ?", options: ["25", "28", "21", "14"] },
  { id: "q53", text: "Which is the odd one out?", options: ["Copper", "Iron", "Gold", "Glass"] },
  { id: "q54", text: "A man looks at a portrait. 'Brothers and sisters I have none, but that man's father is my father's son.' Who is in the portrait?", options: ["Himself", "His son", "His father", "His grandson"] },
  { id: "q55", text: "Water is to Pipe as Electricity is to...", options: ["Wire", "Switch", "Light", "Plug"] },
  { id: "q56", text: "What letter is 2 to the right of the letter 3 to the left of 'G'?", options: ["F", "H", "E", "I"] },
  { id: "q57", text: "If you double a number and add 5, you get 21. What is the number?", options: ["8", "13", "7", "9"] },
  { id: "q58", text: "What starts with 'E', ends with 'E', but only contains one letter?", options: ["Eye", "Envelope", "Eve", "Elite"] },
  { id: "q59", text: "Which is the odd one out?", options: ["Triangle", "Square", "Pentagon", "Circle"] },
  { id: "q60", text: "If all A are B and no B are C, then some A are C.", options: ["True", "False", "Cannot tell", "None"] },
  // 61-70
  { id: "q61", text: "Next in series: 8, 4, 2, 1, ...?", options: ["0", "0.5", "0.25", "-1"] },
  { id: "q62", text: "How many sides does a heptagon have?", options: ["6", "7", "8", "9"] },
  { id: "q63", text: "If you re-arrange 'LGEANND', you get a:", options: ["City", "Country", "Animal", "Ocean"] },
  { id: "q64", text: "A clock shows 3:15. What is the angle between the hands?", options: ["0°", "7.5°", "5°", "10°"] },
  { id: "q65", text: "Fish is to Water as Bird is to...", options: ["Sky", "Tree", "Air", "Nest"] },
  { id: "q66", text: "Which word means 'to grow larger'?", options: ["Contract", "Expand", "Shrink", "Rotate"] },
  { id: "q67", text: "A cube has how many edges?", options: ["6", "8", "12", "16"] },
  { id: "q68", text: "If 5 + 3 = 28, 9 + 1 = 810, then 2 + 1 = ?", options: ["13", "31", "12", "21"] },
  { id: "q69", text: "Which is the odd one out?", options: ["Red", "Yellow", "Blue", "Green"] },
  { id: "q70", text: "What can you catch but not throw?", options: ["Ball", "Cold", "Stick", "Glove"] },
  // 71-80
  { id: "q71", text: "Next in series: 1, 8, 27, 64, ...?", options: ["100", "125", "81", "144"] },
  { id: "q72", text: "What is the square of 13?", options: ["144", "156", "169", "196"] },
  { id: "q73", text: "Which word doesn't fit?", options: ["Car", "Bus", "Train", "Bicycle"] },
  { id: "q74", text: "If you have 4 cubes and stack them, how many faces are hidden?", options: ["6", "8", "12", "10"] },
  { id: "q75", text: "Sword is to Warrior as Pen is to...", options: ["Ink", "Paper", "Writer", "Book"] },
  { id: "q76", text: "Which is the odd one out?", options: ["Acre", "Mile", "Liter", "Foot"] },
  { id: "q77", text: "If a circle has a radius of 5, what is its diameter?", options: ["5", "10", "15", "25"] },
  { id: "q78", text: "What is the next prime after 31?", options: ["33", "35", "37", "39"] },
  { id: "q79", text: "Which word is a synonym for 'Vast'?", options: ["Small", "Huge", "Thin", "Narrow"] },
  { id: "q80", text: "How many seconds in 3 minutes?", options: ["120", "180", "240", "300"] },
  // 81-90
  { id: "q81", text: "Next in series: 4, 9, 14, 19, ...?", options: ["23", "24", "25", "26"] },
  { id: "q82", text: "If 'DOG' is 26, what is 'CAT'?", options: ["24", "26", "22", "20"] },
  { id: "q83", text: "Which is the odd one out?", options: ["Paris", "Berlin", "London", "Texas"] },
  { id: "q84", text: "If 3x = 12, then x + 5 = ?", options: ["4", "9", "7", "11"] },
  { id: "q85", text: "Hand is to Glove as Foot is to...", options: ["Sock", "Shoe", "Toe", "Leg"] },
  { id: "q86", text: "Which word is the opposite of 'Arrive'?", options: ["Stay", "Depart", "Enter", "Wait"] },
  { id: "q87", text: "How many continents are there?", options: ["5", "6", "7", "8"] },
  { id: "q88", text: "What is 1/2 of 1/4 of 80?", options: ["10", "20", "5", "40"] },
  { id: "q89", text: "Which is the odd one out?", options: ["Eagle", "Hawk", "Penguin", "Falcon"] },
  { id: "q90", text: "If 4 people can paint a fence in 3 hours, how long for 2 people?", options: ["1.5 hrs", "6 hrs", "4.5 hrs", "5 hrs"] },
  // 91-100
  { id: "q91", text: "Next in series: 1, 2, 4, 7, 11, ...?", options: ["15", "16", "17", "18"] },
  { id: "q92", text: "What is the capital of France?", options: ["Rome", "Paris", "Madrid", "Lyon"] },
  { id: "q93", text: "Which is the odd one out?", options: ["Dollar", "Euro", "Gold", "Yen"] },
  { id: "q94", text: "If you scramble 'OTLBA', you get a:", options: ["Tool", "Vehicle", "Animal", "Place"] },
  { id: "q95", text: "Tree is to Forest as Person is to...", options: ["House", "Crowd", "Street", "City"] },
  { id: "q96", text: "Which word means 'very small'?", options: ["Massive", "Minute", "Robust", "Giant"] },
  { id: "q97", text: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"] },
  { id: "q98", text: "What is 10 * 10 - 10 / 10?", options: ["90", "9", "99", "1"] },
  { id: "q99", text: "Which is the odd one out?", options: ["January", "April", "Wednesday", "October"] },
  { id: "q100", text: "I have keys but no locks. I have a space but no room. You can enter, but never leave. What am I?", options: ["Keyboard", "Computer", "Library", "Map"] },
];

export const APP_THEME = {
  background: "#0f0f0f",
  primary: "#3b82f6", // Blue
  secondary: "#8b5cf6", // Purple
  accent: "#06b6d4" // Cyan
};
